### ISSUE TITLE
Should support docker-machine based boot2docker

### ISSUE THREAD

**Issue by 1mentat** [domeide/sublime-docker#18]
docker-machine is the preferred way to start local development environments. The status of a known machine name ('dev'?) should be checked instead of boot2docker status.

**Comment by mvisonneau** [comment]
Isn't there a workaround to that ? I am facing the same problem.. :(

**Comment by saulshanabrook** [comment]
Is this possible in any way?

**Comment by l0rd** [comment]
@1mentat @mvisonneau @saulshanabrook thanks for your feedback. That is definitely possible. I didn't had the chance to work on that project in the last months but I should fix that in the next weeks.

**Comment by wiiiimm** [comment]
any update on this?

**Comment by l0rd** [comment]
Hello @williamli,
This has been fixed with 918c4b49d33e23269286020425e4c7596272dfa4 and it's included in v1.3.1 of sublime-docker. I just forgot to close this issue. I'm doing it now but let me know if you still have some concerns.
