### ISSUE TITLE
Sublime Text 3 support

### ISSUE THREAD

**Issue by davidaparicio** [domeide/sublime-docker#2]
Hi @l0rd,

Is Sublime Text 3 supported by the sublime-docker plugin?
Because I installed from Package Control on my Sublime Text 3 64bits (Ubuntu LTS 14.04) and I have this error:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 526, in run_
    return self.run()
  File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 168, in run
TypeError

And if I use the actual version of the repository ('git clone' on ~/.config/sublime-text-3/Packages/User), I have this error:

Unable to find target command: docker_build

Do you have some recommendations?
Best regards

**Comment by l0rd** [comment]
Sublime Text 3 is supported. Anyway I´ll look at that issue tomorrow. Thanks for your feeback

**Comment by l0rd** [comment]
Hi @davidaparicio,

Thanks for your feedback.

We've fixed the problem that caused your second issue (_Unable to find target command_). 

I wasn't able to reproduce your first issue (_TypeError_). Restarting Sublime Text should fix the issue.

Can you please update the plugin and verify if everythig works for you now?

Mario

**Comment by davidaparicio** [comment]
Hi @l0rd,

I tried with the latest version of the package but I had the same error (_Unable to find target command_). But after trying other ways, I found that my path wasn't the right.

I put in ~/.config/sublime-text-3/Packages/**User** instead of ~/.config/sublime-text-3/Packages/

Following the README.md of SublimeLinter/SublimeLinter-for-ST2, the "Packages" directory is located at:
- OS X:
  
  ```
  ~/Library/Application Support/Sublime Text 2/Packages/
  ```
- Linux:
  
  ```
  ~/.config/sublime-text-2/Packages/
  ```
- Windows:
  
  ```
  %APPDATA%/Sublime Text 2/Packages/
  ```

I tried with the Package Control install to see if I have still the _TypeError_ with the latest version, but this issue didn't exist more. 

Nevertheless, with or without Package Control, I have this error now _Docker engine is not running._ :
![docker_hub4](https://cloud.githubusercontent.com/assets/809982/6213258/06eff610-b5ee-11e4-804e-28621829aaf7.PNG)
**But you can see, the service docker.io is currently running...**

For information, I installed Docker from the Ubuntu repository (LTS 14.04):
- sudo apt-get update
- sudo apt-get install docker.io

And I have currently this version:
- Client version: 1.0.1
- Client API version: 1.12
- Go version (client): go1.2.1
- Git commit (client): 990021a
- Server version: 1.0.1
- Server API version: 1.12
- Go version (server): go1.2.1
- Git commit (server): 990021a

David

**Comment by l0rd** [comment]
Ok I thought you were using Sublime Text 3. I'll verify with Sublime Text 2.

**Comment by davidaparicio** [comment]
Sorry, I copy-pasted the readme.MD
I'm currently using Sublime Text 3 (the package folder path is the same) :)

**Comment by l0rd** [comment]
Hello David,

Thanks for your feedback. I usually install Docker with the script 

```
curl -sSL https://get.docker.com/ | sh
```

And this allow me to have last version of Docker.

But installing docker this way the service name is 'docker', not 'docker.io'. That explains why my check to verify if docker was running failed on your machine.

I've now changed the check to include service 'docker.io' and it should work for you too ;-)

Thanks,
Mario

**Comment by davidaparicio** [comment]
Hi @l0rd,

You are welcome. I have just try and it's working now ;-)

Thanks you,
David
