### ISSUE TITLE
Is it necessary for C++ building container to run the executable file after compiling?

### ISSUE THREAD

**Issue by k1xme** [domeide/sublime-docker#22]
I was gonna use this plugin to compile and run my single c++ file program, but turned out it only compile the program. So I added an attribute in the `DockerBuildCommand` class as follow:
    `self.exec_cmd = " && ./a.out" if docker_image == "gcc" else "" # Run the executable file of cpp.`

And appended it to `build_cmd`.

I don't know whether this little modification is needed by you guys.

If so, I will post a PR.

**Comment by mjbright** [comment]
Hi k1xme,

You're right that this is more consistent with the other build/run
scenarii, so you could add this as a PR.

Regards,
Mike.

**Comment by k1xme** [comment]
Hi Mike!

I've created a PR for this modification and a little bug in dockerutils.py. Please merge my PR.

Thanks!

**Comment by k1xme** [comment]
No body follows up with this?

**Comment by mjbright** [comment]
Hi,

Thanks for the reminder ... I'm afraid I'm just leaving on a trip ... I'll
have a look on my return (setting a reminder for that) - sorry for the
delay and thanks for your contribution.

Mike

**Comment by l0rd** [comment]
I'v merged your PR. Thanks @k1xme for your help!
