### ISSUE TITLE
Error starting Sublime Text from OS X launchpad

### ISSUE THREAD

**Issue by divinites** [domeide/sublime-docker#25]
If I start sublime text 3 from the terminal of OSX, everything is fine. However, if I start sublime text from the launchpad, in which case eval "$(docker-machine env default)" does not run, the error occurs when I try to build python scripts using python docker.  I tried to set env directly in python.sublime-build, but received an error which says run(*args) does not recognize the parameter "env".

**Comment by l0rd** [comment]
Thank you @divinites for your feedback. We will look at that issue as soon as possible.

**Comment by dotHTM** [comment]
Ditto for Dock, Application folder etc.

If I start Sublime Text from the terminal session which I've primed Docker with the "Docker QuickStart Terminal.app" or it's internal `bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh`, build works fine.

Any "normal" Mac OS X launch application, and the build complains that it can't connect to Docker (I suppose similar to invoking a Terminal without setting the Docker environment variables with the "Docker QuickStart Terminal.app" shell script.
