### ISSUE TITLE
support of docker-compose instead of fig ?

### ISSUE THREAD

**Issue by xinity** [domeide/sublime-docker#4]
has fig has been renamed docker-compose, i've been wondering if sublime-docker has been updated as well to support docker-compose instead of fig ?

Nice job by the way !!!! :)

**Comment by vdemeester** [comment]
Fig hasn't been renamed in docker compose, that's 2 distinct projects ; But fig won't receive any more big updates, the work is focused now on docker compose. 
There sure will be support for docker compose in the future ;)

**Comment by sammcj** [comment]
I thought docker-compose actually IS fig and they're just renaming it and taking over support of it.

**Comment by vdemeester** [comment]
Well, fig is an _external tool_, develop here : https://github.com/docker/fig.
The idea of docker compose is to have a fig **build-in** the docker client, through a `docker up` command for example. At least I thought that was it.

It's true though that fig command is the same as docker-compose as written in the [fig README](https://github.com/docker/fig)

**Comment by l0rd** [comment]
docker compose (and docker machine) will be supported when _officially_ released by Docker.

**Comment by tcmal** [comment]
Can this be revisited? Would love to use this plugin but considering there's an official alternative, Would rather not use fig.

**Comment by l0rd** [comment]
Hello @OscarOrSomething. I've added Docker Compose support with ba346135d7d8002b5819297b6aef6cf1e8c83d93 but I haven't published it on [packagecontrol.io](https://packagecontrol.io/packages/Docker%20Based%20Build%20Systems). I'll do that now.

**Comment by tcmal** [comment]
Thanks @l0rd, Installed it and am having a problem but I think pr#24 should fix it.

**Comment by l0rd** [comment]
Ok I've merge it and released it again (v 1.3.1). Can you please please test if it's working now?
